### ISSUE TITLE
The subscriber does not receive a retain message

### ISSUE THREAD

**Issue by nmarandi** [bschwind/mqtt-broker#24]
I send a message with the retain flag and after that, I run the subscriber. I expect that the subscriber receives the retain message.

**Comment by bschwind** [comment]
Hi @nmarandi !

This broker is still a work-in-progress, though retained messages are the next feature I'll be working on.

You can track the progress in [this PR](https://github.com/bschwind/mqtt-broker/pull/23) as I work through it.

Since it's currently a hobby project, I don't have a strict timeline to give you but I'll give you a shout when I implement it.

**Comment by phorena** [comment]
MQTT is not useful without the retain feature.

**Comment by bschwind** [comment]
@phorena  would you like to implement it?

**Comment by bschwind** [comment]
Closing in favor of #38
